apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkus-testlauf-3
  janus-idp.io/tekton: quarkus-testlauf-3
  backstage.io/kubernetes-id: quarkus-testlauf-3
  backstage.io/kubernetes-namespace: quarkus-testlauf-3 
  app.kubernetes.io/part-of: quarkus-testlauf-3
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
